feat: social media banner
MariaIllanes/nintendo pull request #3
Opened 2023-09-14 10:32 UTC by Perlo1

2023-09-14 10:56 UTC, dmg310802 requested changes

2023-09-14 10:56 UTC, dmg310802 commented on styles/socialmedia.css
> +    margin-right: 12%;
El logo en la págino original esta más a la izquierda, revisa el margin

2023-09-14 10:56 UTC, dmg310802 commented on styles/socialmedia.css
> +.social-icon img {
los icons estan bien de tamaño, pero el de youtube se ve que el width y el height no se alinean bien.

2023-09-14 10:56 UTC, dmg310802 commented on styles/socialmedia.css
> +.logo {
el display de los icons tiene que ser más cerca de la derecha de la pantalla.

2023-09-15 14:39 UTC, Perlo1 commented on styles/socialmedia.css
> +    margin-right: 12%;
> El logo en la págino original esta más a la izquierda, revisa el margin

cambios visuales realizados cuando puedas revisalos a ver que te parecen

2023-09-18 12:57 UTC, dmg310802 commented on styles/socialmedia.css
> +    margin-right: 12%;
ya realicé los cambios

2023-09-18 13:05 UTC, dmg310802 approved these changes

2023-09-19 10:02 UTC, merged